# Generated by Django 4.2 on 2023-05-03 12:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='описание', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DriveAxel',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='описание', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='описание', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('factoryNumberMachine', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='Заводской номер')),
                ('factoryNumberEngine', models.CharField(max_length=64, unique=True, verbose_name='Заводской номер двигателя')),
                ('factoryNumberTransmission', models.CharField(max_length=64, unique=True, verbose_name='Заводской номер трансмиссии')),
                ('factoryNumberDriveAxel', models.CharField(max_length=64, unique=True, verbose_name='Заводской номер ВО')),
                ('factoryNumberSteringAxel', models.CharField(max_length=64, unique=True, verbose_name='Заводской номер УО')),
                ('supplyContract', models.CharField(max_length=64, verbose_name='Договор поставки')),
                ('shipingDate', models.DateField(default=datetime.date(2023, 5, 3), verbose_name='Дата отгрузки')),
                ('receiver', models.CharField(max_length=64, verbose_name='Получатель')),
                ('deliveryAddress', models.CharField(max_length=256, verbose_name='Адрес доставки')),
                ('equipment', models.CharField(default='стандартная комплектация', max_length=256, verbose_name='Комплектация')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.clientcompany', verbose_name='Компания-клиент')),
                ('driveAxel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.driveaxel', verbose_name='Ведущая ось')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.engine', verbose_name='Модель двигателя')),
            ],
            options={
                'ordering': ['shipingDate'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCompany',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='описание', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ModelMachine',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='описание', max_length=256)),
            ],
            options={
                'verbose_name': 'Model',
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Parts',
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='описание', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='описание', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SteringAxel',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='описание', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='описание', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='описание', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.servicecompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateService', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('operatingTime', models.IntegerField(default=0, verbose_name='Наработка')),
                ('orderNumber', models.CharField(max_length=64, verbose_name='№ Заказ-наряд')),
                ('orderDate', models.DateField(default=datetime.date(2023, 5, 3), verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.machine', verbose_name='Машина')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.servicecompany', verbose_name='Сервисная компания')),
                ('typeOfService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.typeofservice', verbose_name='Тип сервиса')),
            ],
            options={
                'ordering': ['dateService'],
            },
        ),
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='modelMachine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.modelmachine', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='machine',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='machine',
            name='steringAxel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.steringaxel', verbose_name='Управляемая ось'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.transmission', verbose_name='Модель трансмиссии'),
        ),
        migrations.CreateModel(
            name='Complainte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failureDate', models.DateField(default=datetime.date(2023, 5, 3), verbose_name='Дата отказа')),
                ('operatingTime', models.IntegerField(default=0, verbose_name='Наработка')),
                ('failureDescription', models.CharField(default='описание', max_length=256, verbose_name='Описание отказа')),
                ('spareParts', models.CharField(default='зап.части', max_length=256, verbose_name='Запасные части')),
                ('recoveryDate', models.DateField(default=datetime.date(2023, 5, 3), verbose_name='Дата восстановления')),
                ('downTime', models.IntegerField(default=0, verbose_name='Время простоя')),
                ('failurePart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.parts', verbose_name='Узел отказа')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.machine', verbose_name='Машина')),
                ('maintenanceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.maintenancecompany', verbose_name='Компания, проводившая ТО')),
                ('recoveryMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.recoverymethod', verbose_name='Способ восстановления')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.servicecompany', verbose_name='Сервисная компания')),
            ],
            options={
                'ordering': ['downTime'],
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.clientcompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
